name: Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sanity-checks:
    name: Sanity Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Get yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install yarn
        run: yarn install --frozen-lockfile

      - name: Check ESLint
        run: yarn lint:eslint:check

      - name: Check Prettier
        run: yarn lint:prettier:check

      - name: Check Tests
        run: yarn test

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - sanity-checks

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate Release
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          yarn release

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish

      - name: Update Repository
        run: git push --follow-tags origin master
